#!/usr/bin/env bash
# Print "To infinity and beyond" forever; on SIGTERM print "I am invincible!!!" and continue

handle_sigterm() {
    echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
  printf "To infinity and beyond\n"
  sleep 2
done
