#!/usr/bin/env bash
# loop from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

index=1
while [ $index -le 10 ]
do
	index=$((index+=1))
	if [ $index -eq 5 ]
	then
		echo "bad luck"
	elif [ $index -eq 9 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
